package com.example.trip_plan_budget.misc;

public class Utils {
    private static String[] cities = new String[]{
            "Toronto",
            "Montreal",
            "Vancouver",
            "Calgary",
            "Edmonton",
            "Ottawa-Gatineau",
            "Winnipeg",
            "Quebec City",
            "Hamilton",
            "Kitchener",
            "London",
            "Victoria",
            "Halifax",
            "Oshawa",
            "Windsor",
            "Saskatoon",
            "St. Catharines-Niagara Falls",
            "Regina",
            "St. John's",
            "Kelowna",
            "Barrie",
            "Sherbrooke",
            "Guelph",
            "Abbotsford",
            "Kingston",
            "Kanata",
            "Trois-Rivières",
            "Moncton",
            "Chicoutimi-Jonquière",
            "Milton",
            "Red Deer",
            "Brantford",
            "Thunder Bay",
            "White Rock",
            "Nanaimo",
            "Sudbury",
            "Lethbridge",
            "Saint-Jean-sur-Richelieu",
            "Peterborough",
            "Kamloops",
            "Saint-Jérôme",
            "Chilliwack",
            "Sarnia",
            "Châteauguay",
            "Drummondville",
            "Belleville",
            "Fort McMurray",
            "Sault Ste. Marie",
            "Prince George",
            "Medicine Hat",
            "Welland-Pelham",
            "Grande Prairie",
            "Airdrie",
            "Granby",
            "Fredericton",
            "Saint John",
            "Beloeil",
            "North Bay",
            "Saint-Hyacinthe",
            "Brandon",
            "Vernon",
            "Cornwall",
            "Joliette",
            "Courtenay",
            "Charlottetown",
            "Victoriaville",
            "Chatham",
            "Georgetown",
            "St. Thomas",
            "Woodstock",
            "Bowmanville",
            "Salaberry-de-Valleyfield",
            "Shawinigan",
            "Rimouski",
            "Spruce Grove",
            "Sorel",
            "Campbell River",
            "Prince Albert",
            "Penticton",
            "Mission",
            "Leamington",
            "Moose Jaw",
            "Stouffville",
            "Lloydminster",
            "Orillia",
            "Stratford",
            "Orangeville",
            "Cape Breton-Sydney",
            "Bradford",
            "Leduc",
            "Timmins",
            "Okotoks",
            "Saint-Georges",
            "Keswick-Elmhurst Beach",
            "Bolton",
            "Val-d'Or",
            "Cochrane",
            "Quispamsis-Rothesay",
            "Midland",
            "Innisfil"
    };

    public static String[] getCities() {
        return cities;
    }
}
